feat: highlight SQL syntax in Details panel
applandinc/appmap-js pull request #125
Opened 2021-03-16 18:34 UTC by sashahonchar

before: 
![image](https://user-images.githubusercontent.com/17301016/111361966-0207f300-86da-11eb-8896-7c9932bc637e.png)

after:
![image](https://user-images.githubusercontent.com/17301016/111361988-08966a80-86da-11eb-8b78-dfd21c81a49e.png)

fixes: #87

2021-03-17 03:38 UTC, dustinbyrne requested changes
Looks great! Can you add this to the SQL Trace nodes as well?

2021-03-17 13:32 UTC, sashahonchar commented
> Looks great! Can you add this to the SQL Trace nodes as well?

Fixed @dustinbyrne https://github.com/applandinc/appmap-js/pull/125/commits/c4f46f16ae49138a96ee13b0bb6e0a6992ab6d08

2021-03-18 14:37 UTC, dustinbyrne approved these changes

2021-03-18 14:38 UTC, merged

2021-03-22 19:28 UTC, appland-release commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@appland/appmap/v/1.6.0)
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/v1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: