Improve bind events
applandinc/appmap-js pull request #239
Opened 2021-06-01 17:01 UTC by kgilpin

2021-06-02 10:51 UTC, kgilpin commented on packages/models/src/classMap.js
> +function indexCodeObject(co, codeObjects, codeObjectsById) {
This is shared across the constructor and the event registration.

2021-06-02 10:51 UTC, kgilpin commented on packages/models/src/classMap.js
> +    this.constructedCodeObjects = {};
These are the only code objects for which we used `event.toString()` as a key. Other code objects are keyed by location.

2021-06-02 10:52 UTC, kgilpin commented on packages/models/src/classMap.js
> +      if (co.type !== 'package') {
I'm not sure why packages are excluded from this logic, but I've left it.

2021-06-02 10:52 UTC, kgilpin commented on packages/models/src/classMap.js
> +    if (!(event.httpServerRequest || event.httpClientRequest || event.sql)) {
This is a point of weakness in the code; if we add new event types, we may need to add them to this exclusion clause.

2021-06-02 10:52 UTC, kgilpin commented on packages/models/src/classMap.js
> +        const codeObjects = this.codeObjectsAtLocation(location);
This is the way that the agent spec expects events and code objects to be correlated.

2021-06-02 10:53 UTC, kgilpin commented on packages/models/tests/unit/fixtures/spring_petclinic.json
> +      "http_server_request": {
"Function call" fields are removed from this event, per the AppMap spec.

2021-06-03 17:41 UTC, dustinbyrne requested changes
See comments below. `constructedCodeObjects` needs property assignments, or we can safely remove it at a slight performance cost.

2021-06-03 18:21 UTC, kgilpin commented on packages/models/src/classMap.js
> +          };
When I see something nested I know it's not going to be called from anywhere else. So that helps me understand its role within the codebase.

2021-06-03 18:22 UTC, kgilpin commented on packages/models/src/classMap.js
> +    this.constructedCodeObjects = {};
Right, good point. I need to take a look.

2021-06-03 20:09 UTC, kgilpin commented on packages/models/src/classMap.js
> +    this.constructedCodeObjects = {};
I've removed this, so I think this branch is ready to merge now.

2021-06-03 21:43 UTC, dustinbyrne approved these changes

2021-06-03 21:44 UTC, merged

2021-06-03 21:56 UTC, appland-release commented
:tada: This PR is included in version @appland/models-v1.0.6 :tada:

The release is available on:
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/models-v1.0.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-06-09 17:26 UTC, appland-release commented
:tada: This PR is included in version @appland/components-v1.1.6 :tada:

The release is available on:
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/components-v1.1.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: