feat: update Search panel styling
applandinc/appmap-js pull request #245
Opened 2021-06-06 20:24 UTC by sashahonchar

![image](https://user-images.githubusercontent.com/17301016/120938975-e4867a80-c758-11eb-9f68-f8f5d0d601bb.png)

Fixes: #233

2021-06-06 20:45 UTC, kgilpin commented
There is still a lot of empty space here. Can we show the labels as pills?

On Sun, Jun 6, 2021 at 4:24 PM Sasha H. ***@***.***> wrote:

> [image: image]
> <https://user-images.githubusercontent.com/17301016/120938975-e4867a80-c758-11eb-9f68-f8f5d0d601bb.png>
>
> Fixes: #233 <https://github.com/applandinc/appmap-js/issues/233>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/applandinc/appmap-js/pull/245
> Commit Summary
>
>    - feat: update Search panel styling
>
> File Changes
>
>    - *M* packages/components/src/components/DetailsSearch.vue
>    <https://github.com/applandinc/appmap-js/pull/245/files#diff-74bd764cbe881caa352428855feaf3a31a9013d5307a9b03005634039a9f685a>
>    (129)
>    - *M* packages/components/src/scss/_variables.scss
>    <https://github.com/applandinc/appmap-js/pull/245/files#diff-3bc6249a4c30b29f7173510ac0c5cb1af28112f085aa2b146c8857c6c9bf44b6>
>    (1)
>
> Patch Links:
>
>    - https://github.com/applandinc/appmap-js/pull/245.patch
>    - https://github.com/applandinc/appmap-js/pull/245.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/applandinc/appmap-js/pull/245>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVC64EYHXEXD4BEGIPXKTTRPKRRANCNFSM46GK6RHA>
> .
>

2021-06-06 21:25 UTC, sashahonchar commented
Done @kgilpin , PR screenshot was updated as well https://github.com/applandinc/appmap-js/pull/245/commits/58f26a233d0e858a2e82090a86368ba87222fac8

2021-06-29 20:28 UTC, typaulhus requested changes
looks great! There's just a merge conflict that needs to be fixed.

2021-06-30 13:30 UTC, typaulhus approved these changes

2021-06-30 13:40 UTC, merged

2021-06-30 14:02 UTC, appland-release commented
:tada: This PR is included in version @appland/components-v1.5.0 :tada:

The release is available on:
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/components-v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: