feat: re-styled CodeSnippet component
applandinc/appmap-js pull request #328
Opened 2021-09-02 18:28 UTC by sashahonchar

![image](https://user-images.githubusercontent.com/17301016/131897090-7c950541-70c7-45fb-89f8-83065c60b2ce.png)

Fixes #309 
Fixes #326

2021-09-02 21:14 UTC, dustinbyrne requested changes

2021-09-02 21:14 UTC, dustinbyrne commented on packages/components/src/components/Popper.vue
> +  <div class="popper">
This breaks the value hover on nodes in the trace view. Perhaps we need a prop that controls whether or not the popper becomes active on hover or on click?

2021-09-02 23:09 UTC, Daniel-Warner-X commented on packages/components/src/pages/quickstart-docs/InstallAgent.vue
> +        '<b>Copied!</b><br>Paste into your terminal<br>to run the installer',
In the storybook, the success message just says 'Copied to clipboard.' Is there some way I can see the full text of this success message? 
![image](https://user-images.githubusercontent.com/1229326/131927317-1faa25db-84b4-4288-a4ed-31496c49f373.png)

2021-09-03 18:42 UTC, dustinbyrne commented on packages/components/src/components/CodeSnippet.vue
> +        navigator.clipboard.writeText(text);
Can you add an event emit to the root when the user copies text?

2021-09-03 21:58 UTC, merged

2021-09-03 22:12 UTC, appland-release commented
:tada: This PR is included in version @appland/components-v1.12.0 :tada:

The release is available on:
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/components-v1.12.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: