Export parseNormalizeSQL and add joinsCount
applandinc/appmap-js pull request #438
Opened 2021-10-28 16:07 UTC by torchello

2021-10-29 19:58 UTC, dustinbyrne commented
If we're looking to count joins, it looks like it'd be best to add another parser.
https://github.com/applandinc/appmap-js/blob/261e4d9ca8562dc88100af99537fe6561be590fa/packages/models/src/util.js#L451-L463

```ts
sqliteParser(`SELECT * FROM books INNER JOIN authors ON authors.id = books.author_id;`)
```

Results in:
```json
{
  "type": "statement",
  "variant": "list",
  "statement": [
    {
      "type": "statement",
      "variant": "select",
      "result": [
        {
          "type": "identifier",
          "variant": "star",
          "name": "*"
        }
      ],
      "from": {
        "type": "map",
        "variant": "join",
        "source": {
          "type": "identifier",
          "variant": "table",
          "name": "books"
        },
        "map": [
          {
            "type": "join",
            "variant": "inner join",
            "source": {
              "type": "identifier",
              "variant": "table",
              "name": "authors"
            },
            "constraint": {
              "type": "constraint",
              "variant": "join",
              "format": "on",
              "on": {
                "type": "expression",
                "format": "binary",
                "variant": "operation",
                "operation": "=",
                "left": {
                  "type": "identifier",
                  "variant": "column",
                  "name": "authors.id"
                },
                "right": {
                  "type": "identifier",
                  "variant": "column",
                  "name": "books.author_id"
                }
              }
            }
          }
        ]
      }
    }
  ]
}
```

Counting nodes which contain the following k/v pairs looks like it'd give the right count:
```ts
{ type: 'map', variant: 'join' }
```

What do you think about this approach?

2021-10-29 20:13 UTC, kgilpin commented
The question is how reliable is the SQLite parser for MySQL and Postgres.

That’s the sort of thing I was hoping this work would dig into.

On Fri, Oct 29, 2021 at 3:58 PM Dustin Byrne ***@***.***>
wrote:

> If we're looking to count joins, it looks like it'd be best to add another
> parser.
>
> https://github.com/applandinc/appmap-js/blob/261e4d9ca8562dc88100af99537fe6561be590fa/packages/models/src/util.js#L451-L463
>
> sqliteParser(`SELECT * FROM books INNER JOIN authors ON authors.id = books.author_id;`)
>
> Results in:
>
> {
>   "type": "statement",
>   "variant": "list",
>   "statement": [
>     {
>       "type": "statement",
>       "variant": "select",
>       "result": [
>         {
>           "type": "identifier",
>           "variant": "star",
>           "name": "*"
>         }
>       ],
>       "from": {
>         "type": "map",
>         "variant": "join",
>         "source": {
>           "type": "identifier",
>           "variant": "table",
>           "name": "books"
>         },
>         "map": [
>           {
>             "type": "join",
>             "variant": "inner join",
>             "source": {
>               "type": "identifier",
>               "variant": "table",
>               "name": "authors"
>             },
>             "constraint": {
>               "type": "constraint",
>               "variant": "join",
>               "format": "on",
>               "on": {
>                 "type": "expression",
>                 "format": "binary",
>                 "variant": "operation",
>                 "operation": "=",
>                 "left": {
>                   "type": "identifier",
>                   "variant": "column",
>                   "name": "authors.id"
>                 },
>                 "right": {
>                   "type": "identifier",
>                   "variant": "column",
>                   "name": "books.author_id"
>                 }
>               }
>             }
>           }
>         ]
>       }
>     }
>   ]
> }
>
> Counting nodes which contain the following k/v pairs looks like it'd give
> the right count:
>
> { type: 'map', variant: 'join' }
>
> What do you think about this approach?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/applandinc/appmap-js/pull/438#issuecomment-955013231>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVC65V7D4BJZSXXT75OS3UJL4FLANCNFSM5G5ISSJQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-29 20:17 UTC, kgilpin commented
How about relationCount? @divide

On Fri, Oct 29, 2021 at 12:18 PM Alex Torchenko ***@***.***>
wrote:

> @kgilpin <https://github.com/kgilpin> @dustinbyrne
> <https://github.com/dustinbyrne> I've changed the property to
> nonUniqueTablesCount (let me know if you see a better name). Also, added
> a test for self join (works fine):
>
> https://github.com/applandinc/appmap-js/pull/438/files#diff-a08ce4b00cc953628734678a9e8313e5e5c244e6856bf389379afe531f50fae8R66-R74
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/applandinc/appmap-js/pull/438#issuecomment-954875017>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVC6YY3W2HJTNRETGGVX3UJLCO7ANCNFSM5G5ISSJQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-29 21:23 UTC, torchello commented
I think @dustinbyrne's suggestion makes sense 👍 Please check the last commit. I've added another test and it seems to be a more consistent approach in terms of what is "join" and how do we count them (we rely on AST and don't treat sub-queries as joins now).

@kgilpin I will add some more tests to cover mysql/postgresql compatibility.

2021-11-01 13:17 UTC, dividedmind commented on packages/models/src/util.js
> +      joinsCount: tables.length - 1,
The second query in fact has a join.

2021-11-01 13:20 UTC, dividedmind commented
> I think @dustinbyrne's suggestion makes sense +1 Please check the last commit. I've added another test and it seems to be a more consistent approach in terms of what is "join" and how do we count them (we rely on AST and don't treat sub-queries as joins now).
> 
> @kgilpin I will add some more tests to cover mysql/postgresql compatibility.

This won't catch `SELECT foo FROM bar, baz WHERE bar.baz_id = baz.id` which is unequivocally a join.

2021-11-01 13:25 UTC, dividedmind requested changes
As mentioned, this won't catch even some trivial joins like `SELECT * FROM a, b`.

2021-11-01 13:56 UTC, torchello commented
@dividedmind The examples you provided are covered. In AST they are represented by a cross join:
```
sqliteParser(`SELECT books.*, authors.* FROM books, authors`)
{
  "type": "statement",
  "variant": "list",
  "statement": [
    {
      "type": "statement",
      "variant": "select",
      "result": [
        {
          "type": "identifier",
          "variant": "star",
          "name": "books.*"
        },
        {
          "type": "identifier",
          "variant": "star",
          "name": "authors.*"
        }
      ],
      "from": {
        "type": "map",
        "variant": "join",
        "source": {
          "type": "identifier",
          "variant": "table",
          "name": "books"
        },
        "map": [
          {
            "type": "join",
            "variant": "cross join",
            "source": {
              "type": "identifier",
              "variant": "table",
              "name": "authors"
            }
          }
        ]
      }
    }
  ]
}
```

Check this test case:
https://github.com/applandinc/appmap-js/pull/438/files#diff-a08ce4b00cc953628734678a9e8313e5e5c244e6856bf389379afe531f50fae8R55-R64

2021-11-01 16:16 UTC, dividedmind requested changes
> @dividedmind The examples you provided are covered. In AST they are represented by a cross join

Ah, you're right, I haven't noticed that! Sorry, I stand corrected :) In this case, the only thing that bothers me is the name: it should be `joinCount`, without the `s` :)

2021-11-01 16:34 UTC, torchello commented
@dividedmind Fixed. Please check again 🤞 

@kgilpin I added some more tests to cover different types of joins. Apparently, most of the changes in SQLite/MySQL/PostgresQL syntax are related to data types and queries to manage schema, so not affecting "regular" queries and this specific joins use case.

2021-11-01 17:33 UTC, dividedmind approved these changes
Looks ok. Do we have any tests that cover MySQL syntax? In particular, the usage of backticks to quote identifiers?

2021-11-01 17:55 UTC, kgilpin commented
> Looks ok. Do we have any tests that cover MySQL syntax? In particular, the usage of backticks to quote identifiers?

I would love to see as many of these edge cases covered as possible!

2021-11-01 19:38 UTC, dividedmind commented
One other question: why export `parseNormalizeSQL` instead of using `normalizeSQL` in the client? It seems to me that `parseNormalizeSQL` is an implementation detail.

2021-11-01 20:43 UTC, merged

2021-11-01 20:58 UTC, appland-release commented
:tada: This PR is included in version @appland/models-v1.6.0 :tada:

The release is available on:
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/models-v1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-11-01 20:59 UTC, appland-release commented
:tada: This PR is included in version @appland/appmap-v3.11.0 :tada:

The release is available on:
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/appmap-v3.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: