feat: filter events in Trace by label
applandinc/appmap-js pull request #475
Opened 2021-12-01 20:46 UTC by sashahonchar

![image](https://user-images.githubusercontent.com/1647695/144309924-c9902311-d5d5-432b-a0c8-958d38b5d8d0.png)

Fixes #464

2021-12-01 22:21 UTC, kgilpin commented on packages/components/src/pages/VsCodeExtension.vue
> +                  nodes.push(event.id);
Suggest using a Set to deal with events that match more than one filter expression.

2021-12-02 16:18 UTC, kgilpin requested changes

2021-12-02 16:18 UTC, kgilpin commented on packages/components/src/pages/VsCodeExtension.vue
>                if (!Number.isNaN(eventId) && knownEventIds.includes(eventId)) {
Looking up an id in an Array is inefficient - use a Set instead.

2021-12-02 22:49 UTC, dustinbyrne approved these changes

2021-12-02 22:50 UTC, merged

2021-12-02 23:14 UTC, appland-release commented
:tada: This PR is included in version @appland/components-v1.17.0 :tada:

The release is available on:
- `@appland/components-v1.17.0`
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/components-v1.17.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: