feat: Scan with api key
applandinc/appmap-js pull request #498
Opened 2021-12-14 21:55 UTC by kgilpin

Supports integration of API key into the scanner.

2022-01-03 19:00 UTC, dustinbyrne requested changes
Looking good. I've added a couple of minor comments below.

2022-01-03 19:00 UTC, dustinbyrne commented on packages/client/src/types.d.ts
> +};
Type declaration files are meant to describe JavaScript types, so we shouldn't need one to describe types in this package. Can these types find better homes in another location? I'd recommend they be placed with the API that returns them, but I'm fine with anything you can come up with.

2022-01-05 16:23 UTC, kgilpin commented on packages/client/src/handleError.ts
> +      chunks.push(chunk as never);
One thing I don't understand is why I also have to cast chunk to Buffer since response.read seems to return `any`.

2022-01-05 16:24 UTC, kgilpin commented on packages/client/src/handleError.ts
> +      chunks.push(chunk as never);
It seems like TypeScript is really just not dealing well with this whole section: ```  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  const contentType = (response.headers['content-type'] || '') as string;
  if (contentType.startsWith('application/json')) {
    const chunks = [] as Buffer[];
    for await (const chunk of response) {
      chunks.push(chunk as Buffer);
    }
    const responseBody = Buffer.concat(chunks).toString();
    responseData = JSON.parse(responseBody) as ErrorResponse;
  }
```

2022-01-05 17:50 UTC, dustinbyrne commented on packages/client/src/handleError.ts
> +      chunks.push(chunk as never);
The cast to `Buffer` is only required by ESLint AFAIK. TypeScript should happily accept `any` as a `Buffer` without an explicit cast. I'm guessing it's only required as an acknowledgement that you're using an unsafe type, but you're stating that you know what the actual type is at runtime.

2022-01-05 17:56 UTC, dustinbyrne approved these changes

2022-01-05 18:19 UTC, merged

2022-01-05 18:37 UTC, appland-release commented
:tada: This PR is included in version @appland/models-v1.10.0 :tada:

The release is available on:
- `@appland/models-v1.10.0`
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/models-v1.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-01-05 18:37 UTC, appland-release commented
:tada: This PR is included in version @appland/client-v1.1.0 :tada:

The release is available on:
- `@appland/client-v1.1.0`
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/client-v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-01-05 18:37 UTC, appland-release commented
:tada: This PR is included in version @appland/components-v1.18.2 :tada:

The release is available on:
- `@appland/components-v1.18.2`
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/components-v1.18.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-01-05 18:38 UTC, appland-release commented
:tada: This PR is included in version @appland/appmap-v3.14.7 :tada:

The release is available on:
- `@appland/appmap-v3.14.7`
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/appmap-v3.14.7)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: