feat: get/set global filters state with state API
applandinc/appmap-js pull request #509
Opened 2021-12-28 21:11 UTC by sashahonchar

Fixes #Default filters can be modified via setState API

2022-01-03 19:47 UTC, dustinbyrne requested changes
The change looks good but this needs test cases.

2022-01-10 17:18 UTC, sashahonchar commented
@dustinbyrne  Found a bug in code and added unit test. https://github.com/applandinc/appmap-js/pull/509/commits/b5a1835fa8ac26ccaad3d22f7dfa106e45aeff92

2022-01-11 18:04 UTC, dustinbyrne requested changes
Looking better. We'll also need an updated test for `getState`, where the filters contain non-default values. Plus a comment below.

2022-01-11 18:04 UTC, dustinbyrne commented on packages/components/tests/unit/VsCodeExtension.spec.js
> +    expect(wrapper.vm.filters.declutter.hideName.on).toBe(false);
`limitRootEvents` / `hideUnlabeled` / `hideName` properties have no test coverage in this case.

2022-01-12 20:32 UTC, dustinbyrne approved these changes

2022-01-12 20:32 UTC, merged

2022-01-12 20:50 UTC, appland-release commented
:tada: This PR is included in version @appland/components-v1.20.0 :tada:

The release is available on:
- `@appland/components-v1.20.0`
- `NPM publish`
- [GitHub release](https://github.com/applandinc/appmap-js/releases/tag/%40appland/components-v1.20.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: