fix: User can configure extended RR URL
applandinc/appmap-js pull request #609
Opened 2022-06-06 17:37 UTC by kgilpin

Even if the server process can't be found in the process table, the user can elect to continue with remote recording and specify extended options for the URL connection.

2022-06-06 20:28 UTC, apotterri requested changes
One minor wording change, looks good otherwise. Thanks for doing this.

2022-06-06 20:28 UTC, apotterri commented on packages/cli/src/cmds/record/prompt/continueWithRequestOptionConfiguration.ts
> +      `Otherwise you start over by reconfiguring the host and port.`
Seems like a word is missing here? "Otherwise you can", "should", "must"?

2022-06-06 21:09 UTC, apotterri approved these changes

2022-06-07 03:31 UTC, merged

2022-10-11 07:20 UTC, kgilpin commented
Yes, right. Should be “can”

On Mon, Jun 6, 2022 at 4:28 PM Alan Potter ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> One minor wording change, looks good otherwise. Thanks for doing this.
> ------------------------------
>
> In
> packages/cli/src/cmds/record/prompt/continueWithRequestOptionConfiguration.ts
> <https://github.com/applandinc/appmap-js/pull/609#discussion_r890527623>:
>
> > +export enum ConfigurationAction {
> +  HostAndPort = 'Reconfigure host and port',
> +  RequestOptions = 'Keep the host and port, and configure additional connection options',
> +}
> +
> +export default async function continueWithRequestOptionConfiguration(): Promise<ConfigurationAction> {
> +  UI.progress(
> +    `I can't find your AppMap server process on port ${
> +      (await requestOptions()).port
> +    }.`
> +  );
> +  UI.progress('');
> +  UI.progress(
> +    `If you're sure it's running on that port, we can continue with extra configuration ` +
> +      `options that may enable me to connect to the agent. ` +
> +      `Otherwise you start over by reconfiguring the host and port.`
>
> Seems like a word is missing here? "Otherwise you can", "should", "must"?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/applandinc/appmap-js/pull/609#pullrequestreview-997183721>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVC65LTEWBQKWUHWIXLXTVNZNOZANCNFSM5YACIDFQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>